//! Precompile the Scarlet stdlib at build time into `$OUT_DIR/stdlib_generated.rs`,
//! entirely `const`/`static` arrays: no serde, no runtime deserialization —
//! the binary's `.rodata` is the stdlib.
//!
//! Any error in `src/std/**`, including `PreludeBindings::capture` shape
//! mismatches, fails the cargo build with the diagnostic text.

use std::fmt::Write as _;
use std::path::PathBuf;

use scarlet_core::static_ir::flatten::{FlatPools, flatten};
use scarlet_core::static_ir::{SConst, Slice};
use scarlet_core::types::{
    ArenaSlice, DefinitionLocation, EntityKind, QuantVar, Scheme, StrId, TypeBody, TypeInfo,
    TypeNode, ValueKind,
};
use scarlet_core::{PreludeBindings, TypeId};

fn main() {
    // One rerun-if-changed per file: a directory path alone does not reliably
    // pick up edits to existing files.
    for entry in walk_std("../scarlet_core/src/std") {
        println!("cargo:rerun-if-changed={}", entry.display());
    }
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    let (pre, engine) = match scarlet_core::precompile_stdlib() {
        Ok(p) => p,
        Err(e) => panic!("\n\n{e}\n"),
    };
    let pools = flatten(&pre, &engine);

    let mut src = String::with_capacity(256 * 1024);
    writeln!(src, "// generated by build.rs — do not edit").unwrap();
    writeln!(
        src,
        "use scarlet_core::static_ir::*;\n\
         use scarlet_core::types::*;\n\
         use scarlet_core::bytecode::{{Instruction, Op}};\n\
         use scarlet_core::{{PreludeBindings, TypeRef, CtorRef, TypeId}};\n"
    )
    .unwrap();

    emit_pools(&mut src, &pools);

    writeln!(
        src,
        "pub static STDLIB: StaticStdlib = StaticStdlib {{\n    \
         str_pool: STR_POOL, str_slice_pool: STR_SLICE_POOL, byte_pool: BYTE_POOL,\n    \
         nodes: NODES, children: CHILDREN,\n    \
         quants: QUANTS, str_slices: STR_SLICES, type_params: TYPE_PARAMS, variant_fields: VARIANT_FIELDS, variants: VARIANTS,\n    \
         schemes: SCHEMES, typeinfos: TYPEINFOS,\n    \
         stypeexport_pool: STYPEEXPORT_POOL, sexport_pool: SEXPORT_POOL, modules: MODULES, typeinfo_by_name: TYPEINFO_BY_NAME,\n    \
         code: CODE, functions: FUNCTIONS, constants: CONSTANTS,\n    \
         prelude: &PRELUDE, reserved: RESERVED, next_type_id: NEXT_TYPE_ID, local_count: STDLIB_LOCAL_COUNT,\n\
         }};"
    )
    .unwrap();

    std::fs::write(out_dir.join("stdlib_generated.rs"), &src)
        .unwrap_or_else(|e| panic!("write stdlib_generated.rs failed: {e}"));
}

fn walk_std(root: &str) -> Vec<PathBuf> {
    let mut out = vec![PathBuf::from(root)];
    let mut stack = vec![PathBuf::from(root)];
    while let Some(dir) = stack.pop() {
        for entry in
            std::fs::read_dir(&dir).unwrap_or_else(|e| panic!("build.rs: read_dir {dir:?}: {e}"))
        {
            let entry = entry.unwrap_or_else(|e| panic!("build.rs: walk {dir:?}: {e}"));
            let p = entry.path();
            if p.is_dir() {
                stack.push(p.clone());
            }
            out.push(p);
        }
    }
    out
}

fn q(s: &str) -> String {
    format!("{s:?}")
}

fn tid(id: TypeId) -> String {
    format!("TypeId({})", id.0)
}

/// `lit!(Type: field = expr, ...)` → `"Type { field: <expr>, ... }"`.
macro_rules! lit {
    ($T:ident : $($f:ident = $e:expr),+ $(,)?) => {
        format!(concat!(stringify!($T), " {{ ", $(stringify!($f), ": {}, ",)+ "}}"), $($e),+)
    };
}

fn slice<T>(sl: Slice<T>) -> String {
    format!("Slice::new({}, {})", sl.start, sl.len)
}

fn aslice<P>(sl: ArenaSlice<P>) -> String {
    format!("ArenaSlice::new({}, {})", sl.start, sl.len)
}

fn typenode(n: &TypeNode) -> String {
    match *n {
        TypeNode::Var(id) => format!("TypeNode::Var({id})"),
        TypeNode::Bound(i) => format!("TypeNode::Bound({i})"),
        TypeNode::Con { id, name, args } => {
            format!(
                "TypeNode::Con {{ id: {}, name: {name:?}, args: {} }}",
                tid(id),
                aslice(args)
            )
        }
        TypeNode::Fun { params, ret } => {
            format!(
                "TypeNode::Fun {{ params: {}, ret: {ret:?} }}",
                aslice(params)
            )
        }
        TypeNode::Tuple { elems } => format!("TypeNode::Tuple {{ elems: {} }}", aslice(elems)),
    }
}

fn emit_static_slice<I: Iterator<Item = String>>(out: &mut String, name: &str, ty: &str, items: I) {
    writeln!(out, "pub static {name}: &[{ty}] = &[").unwrap();
    for it in items {
        writeln!(out, "    {it},").unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn emit_nums<T: std::fmt::Display>(out: &mut String, name: &str, ty: &str, items: &[T]) {
    emit_static_slice(out, name, ty, items.iter().map(T::to_string));
}

fn emit_strs<S: AsRef<str>>(out: &mut String, name: &str, items: &[S]) {
    emit_static_slice(out, name, "&str", items.iter().map(|s| q(s.as_ref())));
}

fn emit_prelude(out: &mut String, p: &PreludeBindings) {
    writeln!(
        out,
        "pub const PRELUDE: PreludeBindings = PreludeBindings {{"
    )
    .unwrap();
    for (n, r) in p.type_fields() {
        let v = lit!(TypeRef: id = tid(r.id), name = format_args!("{:?}", r.name));
        writeln!(out, "    {n}: {v},").unwrap();
    }
    for (n, c) in p.ctor_fields() {
        let v =
            lit!(CtorRef: type_id = tid(c.type_id), variant_idx = c.variant_idx, arity = c.arity);
        writeln!(out, "    {n}: {v},").unwrap();
    }
    writeln!(out, "}};").unwrap();
}

fn opt_constraint(c: Option<scarlet_core::types::Constraint>) -> String {
    match c {
        Some(c) => format!("Some(Constraint::{c:?})"),
        None => "None".into(),
    }
}

/// Emit every `StaticStdlib` field from the flattened pools.
fn emit_pools(out: &mut String, p: &FlatPools) {
    emit_prelude(out, &p.prelude);
    emit_strs(out, "RESERVED", &p.reserved);
    writeln!(
        out,
        "pub const NEXT_TYPE_ID: TypeId = {};",
        tid(p.next_type_id)
    )
    .unwrap();
    writeln!(
        out,
        "pub const STDLIB_LOCAL_COUNT: i32 = {};",
        p.local_count
    )
    .unwrap();

    emit_strs(out, "STR_POOL", &p.str_pool);
    emit_static_slice(
        out,
        "STR_SLICE_POOL",
        "StrIdx",
        p.str_slice_pool.iter().map(|i| format!("{i:?}")),
    );
    emit_nums(out, "BYTE_POOL", "u8", &p.byte_pool);

    emit_static_slice(out, "NODES", "TypeNode", p.nodes.iter().map(typenode));
    emit_static_slice(
        out,
        "CHILDREN",
        "Ty",
        p.children.iter().map(|t| format!("{t:?}")),
    );
    emit_static_slice(out, "QUANTS", "QuantVar", p.quants.iter().map(quantvar));
    emit_static_slice(
        out,
        "STR_SLICES",
        "StrId",
        p.str_slices.iter().map(|s| format!("{s:?}")),
    );
    emit_static_slice(
        out,
        "TYPE_PARAMS",
        "TypeParam",
        p.type_params
            .iter()
            .map(|tp| lit!(TypeParam: name = format_args!("{:?}", tp.name), id = -1)),
    );
    emit_static_slice(
        out,
        "VARIANT_FIELDS",
        "VariantField",
        p.variant_fields
            .iter()
            .map(|f| lit!(VariantField: label = format_args!("{:?}", f.label), ty = format_args!("{:?}", f.ty))),
    );
    emit_static_slice(
        out,
        "VARIANTS",
        "Variant",
        p.variants
            .iter()
            .map(|v| lit!(Variant: name = format_args!("{:?}", v.name), fields = aslice(v.fields))),
    );

    emit_static_slice(out, "SCHEMES", "Scheme", p.schemes.iter().map(scheme));
    emit_static_slice(
        out,
        "TYPEINFOS",
        "TypeInfo",
        p.typeinfos.iter().map(typeinfo),
    );

    emit_static_slice(
        out,
        "STYPEEXPORT_POOL",
        "STypeExport",
        p.stypeexport_pool.iter().map(|e| {
            lit!(STypeExport: name = format_args!("{:?}", e.name),
                 info = format_args!("{:?}", e.info),
                 def = def_lit(e.def),
                 doc = format_args!("{:?}", e.doc))
        }),
    );
    emit_static_slice(
        out,
        "SEXPORT_POOL",
        "SExport",
        p.sexport_pool.iter().map(|e| {
            lit!(SExport: name = format_args!("{:?}", e.name),
                scheme = format_args!("{:?}", e.scheme),
                local_slot = format_args!("{:?}", e.local_slot),
                param_names = slice(e.param_names),
                doc = format_args!("{:?}", e.doc))
        }),
    );
    emit_static_slice(
        out,
        "MODULES",
        "(&str, SModule)",
        p.modules.iter().map(|(k, m)| {
            format!(
                "({}, SModule {{ types: {}, values: {}, private_names: {}, path: {}, doc: {:?} }})",
                q(k),
                slice(m.types),
                slice(m.values),
                slice(m.private_names),
                slice(m.path),
                m.doc
            )
        }),
    );
    emit_static_slice(
        out,
        "TYPEINFO_BY_NAME",
        "(&str, TypeInfoIdx)",
        p.typeinfo_by_name
            .iter()
            .map(|(n, i)| format!("({}, {:?})", q(n), i)),
    );

    emit_static_slice(
        out,
        "CODE",
        "Instruction",
        p.code.iter().map(|i| {
            lit!(Instruction: op = format_args!("Op::{:?}", i.op), operand = i.operand, a = i.a, b = i.b)
        }),
    );
    emit_static_slice(
        out,
        "FUNCTIONS",
        "SFunction",
        p.functions.iter().map(|f| {
            lit!(SFunction: name = format_args!("{:?}", f.name), arity = f.arity, locals = f.locals,
                 capture_count = f.capture_count, code_start = f.code_start, code_len = f.code_len)
        }),
    );
    emit_static_slice(out, "CONSTANTS", "SConst", p.constants.iter().map(sconst));
}

fn quantvar(qv: &QuantVar) -> String {
    let name = if qv.name == StrId::NONE {
        "StrId::NONE".into()
    } else {
        format!("{:?}", qv.name)
    };
    lit!(QuantVar: constraint = opt_constraint(qv.constraint), name = name, origin_id = "None")
}

fn valuekind(k: ValueKind) -> String {
    match k {
        ValueKind::Local => "ValueKind::Local".into(),
        ValueKind::ModuleFn => "ValueKind::ModuleFn".into(),
        ValueKind::Builtin { op } => format!("ValueKind::Builtin {{ op: Op::{op:?} }}"),
        ValueKind::Constructor {
            type_name,
            type_id,
            variant_idx,
            arity,
            field_labels,
        } => format!(
            "ValueKind::Constructor {{ type_name: {type_name:?}, type_id: {}, variant_idx: {variant_idx}, arity: {arity}, field_labels: {} }}",
            tid(type_id),
            aslice(field_labels)
        ),
    }
}

fn entitykind(e: EntityKind) -> &'static str {
    match e {
        EntityKind::Value => "EntityKind::Value",
        EntityKind::Function => "EntityKind::Function",
        EntityKind::Constant => "EntityKind::Constant",
        EntityKind::Constructor => "EntityKind::Constructor",
        EntityKind::Type => "EntityKind::Type",
        EntityKind::ModuleAlias => "EntityKind::ModuleAlias",
        EntityKind::Field => "EntityKind::Field",
    }
}

/// Emit the declaring `DefinitionLocation` so goto-def can land inside a
/// precompiled `scarlet/*` module. Its `module` slice indexes the static
/// string-slice pool, which `seed_static` memcpies back as the live arena's
/// prefix, so the location stays valid.
fn def_lit(d: Option<DefinitionLocation>) -> String {
    match d {
        None => "None".to_string(),
        Some(dl) => format!(
            "Some(DefinitionLocation {{ line: {}, column: {}, end_col: {}, module: {}, entity: {} }})",
            dl.line,
            dl.column,
            dl.end_col,
            aslice(dl.module),
            entitykind(dl.entity),
        ),
    }
}

fn scheme(s: &Scheme) -> String {
    lit!(Scheme: quantified = aslice(s.quantified), ty = format_args!("{:?}", s.ty), kind = valuekind(s.kind), def = def_lit(s.def))
}

fn typeinfo(ti: &TypeInfo) -> String {
    let body = match ti.body {
        TypeBody::External => "TypeBody::External".into(),
        TypeBody::Unresolved => panic!(
            "build.rs: stdlib type has Unresolved body after precompile — hydration missed it"
        ),
        TypeBody::Alias { target } => format!("TypeBody::Alias {{ target: {target:?} }}"),
        TypeBody::Custom { variants } => {
            format!("TypeBody::Custom {{ variants: {} }}", aslice(variants))
        }
    };
    lit!(TypeInfo: id = tid(ti.id), name = format_args!("{:?}", ti.name), module = aslice(ti.module),
         type_params = aslice(ti.type_params), body = body)
}

fn sconst(c: &SConst) -> String {
    match *c {
        SConst::Int(n) => format!("SConst::Int({n}i64)"),
        SConst::Float(f) => format!("SConst::Float({}f64)", float_lit(f)),
        SConst::Bool(b) => format!("SConst::Bool({b})"),
        SConst::Str(i) => format!("SConst::Str({i:?})"),
        SConst::StrArray(sl) => format!("SConst::StrArray({})", slice(sl)),
        SConst::Binary(sl, bit_len) => format!("SConst::Binary({}, {bit_len}u64)", slice(sl)),
    }
}

fn float_lit(f: f64) -> String {
    if f.is_nan() {
        "f64::NAN".into()
    } else if f.is_infinite() {
        if f > 0.0 {
            "f64::INFINITY"
        } else {
            "f64::NEG_INFINITY"
        }
        .into()
    } else {
        // Debug formatting of f64 is round-trippable.
        format!("{f:?}")
    }
}
