["scarlet (bin scarlet)"]
"wildcard_local_enum:crates/scarlet/src/main.rs" = 1

[scarlet_core]
"wildcard_local_enum:crates/scarlet_core/src/bytecode/analysis.rs" = 1
"wildcard_local_enum:crates/scarlet_core/src/core_ir/clif.rs" = 3
"wildcard_local_enum:crates/scarlet_core/src/core_ir/emit.rs" = 2
"wildcard_local_enum:crates/scarlet_core/src/core_ir/lower.rs" = 4
"wildcard_local_enum:crates/scarlet_core/src/core_ir/perceus.rs" = 1
"wildcard_local_enum:crates/scarlet_core/src/reference/mod.rs" = 2
"wildcard_local_enum:crates/scarlet_core/src/typed_ir/rty.rs" = 3

[scarlet_syntax]
"wildcard_local_enum:crates/scarlet_syntax/src/desugar.rs" = 1
"wildcard_local_enum:crates/scarlet_syntax/src/formatter/doc.rs" = 3
"wildcard_local_enum:crates/scarlet_syntax/src/parser/mod.rs" = 1

[scarlet_types]
"wildcard_local_enum:crates/scarlet_types/src/types/exhaustiveness.rs" = 4
"wildcard_local_enum:crates/scarlet_types/src/types/hydrator.rs" = 1
"wildcard_local_enum:crates/scarlet_types/src/types/infer.rs" = 3

[scarlet_vm]
"wildcard_local_enum:crates/scarlet_vm/src/vm/exec.rs" = 2
