use std::fmt;

use super::keywords::Keyword;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Kind {
    Eof,
    Error,
    Identifier,
    LiteralNumber,
    LiteralString,
    InterpStringStart,
    InterpStringPart,
    InterpStringEnd,
    LogicalAnd,
    LogicalOr,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseNot,
    Keyword(Keyword),
    PuncArrow,
    PuncComma,
    PuncColon,
    PuncSemicolon,
    PuncDot,
    PuncDotdot,
    PuncOpenParen,
    PuncCloseParen,
    PuncOpenBrace,
    PuncCloseBrace,
    PuncOpenBracket,
    PuncCloseBracket,
    BinOpen,
    BinClose,
    PuncQuestionMark,
    PuncExclamationMark,
    PuncAt,
    PuncEquals,
    PuncEqualsComparator,
    PuncNotEqual,
    PuncGt,
    PuncLt,
    PuncGte,
    PuncLte,
    PuncPlus,
    PuncPlusplus,
    PuncMinus,
    PuncMinusminus,
    PuncMul,
    PuncDiv,
    PuncMod,
}

impl fmt::Display for Kind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Kind::Eof => "EOF",
            Kind::Error => "<error>",
            Kind::Identifier => "identifier",
            Kind::LiteralNumber => "number",
            Kind::LiteralString => "string",
            Kind::InterpStringStart => "interpolated string start",
            Kind::InterpStringPart => "interpolated string part",
            Kind::InterpStringEnd => "interpolated string end",
            Kind::LogicalAnd => "&&",
            Kind::LogicalOr => "||",
            Kind::BitwiseAnd => "&",
            Kind::BitwiseOr => "|",
            Kind::BitwiseXor => "^",
            Kind::BitwiseNot => "~",
            Kind::Keyword(kw) => kw.text(),
            Kind::PuncArrow => "->",
            Kind::PuncComma => ",",
            Kind::PuncColon => ":",
            Kind::PuncSemicolon => ";",
            Kind::PuncDot => ".",
            Kind::PuncDotdot => "..",
            Kind::PuncOpenParen => "(",
            Kind::PuncCloseParen => ")",
            Kind::PuncOpenBrace => "{",
            Kind::PuncCloseBrace => "}",
            Kind::PuncOpenBracket => "[",
            Kind::PuncCloseBracket => "]",
            Kind::BinOpen => "<<",
            Kind::BinClose => ">>",
            Kind::PuncQuestionMark => "?",
            Kind::PuncExclamationMark => "!",
            Kind::PuncAt => "@",
            Kind::PuncEquals => "=",
            Kind::PuncEqualsComparator => "==",
            Kind::PuncNotEqual => "!=",
            Kind::PuncGt => ">",
            Kind::PuncLt => "<",
            Kind::PuncGte => ">=",
            Kind::PuncLte => "<=",
            Kind::PuncPlus => "+",
            Kind::PuncPlusplus => "++",
            Kind::PuncMinus => "-",
            Kind::PuncMinusminus => "--",
            Kind::PuncMul => "*",
            Kind::PuncDiv => "/",
            Kind::PuncMod => "%",
        };
        f.write_str(s)
    }
}
