//! Constructor visibility has to survive the precompiled stdlib blob, not just
//! the in-memory compile. `wire`'s descriptor builder reads it to decide
//! whether it may build a value by constructor from outside the declaring
//! module, and every stdlib type reaches it through this blob.
//!
//! These tests live here rather than in `scarlet_core` because the blob is
//! generated by `crates/scarlet/build.rs` and only this crate consumes it. A
//! round trip inside `scarlet_core` would exercise the codec while leaving the
//! codegen — the half that can silently emit a constant — untested.

use scarlet::STDLIB;

fn ctors_public(name: &str) -> Option<bool> {
    let idx = STDLIB
        .typeinfo_by_name
        .iter()
        .find(|(n, _)| *n == name)
        .unwrap_or_else(|| panic!("no stdlib type named {name}"))
        .1;
    STDLIB.typeinfos[idx.0 as usize].ctors_public()
}

/// `pub opaque type Decimal` in `scarlet/decimal`. Bytes could otherwise
/// produce a scale the module never allows, which is what `opaque` exists to
/// forbid.
#[test]
fn an_opaque_stdlib_type_reports_private_constructors() {
    assert_eq!(ctors_public("Decimal"), Some(false));
}

/// `pub type Option(a) { Some(a) None }`. Paired with the case above on
/// purpose: a codegen that emits a constant fails exactly one of the two,
/// whichever constant it picked, and passes the other.
#[test]
fn a_public_stdlib_type_reports_public_constructors() {
    assert_eq!(ctors_public("Option"), Some(true));
}

/// The blob is not uniform. This is the direct statement of what the pair
/// above tests indirectly: if `build.rs` ever stops threading the real value,
/// every type reads the same and this goes red without depending on which
/// two types were picked.
#[test]
fn the_blob_carries_both_answers() {
    let mut public = 0usize;
    let mut private = 0usize;
    for ti in STDLIB.typeinfos {
        match ti.ctors_public() {
            Some(true) => public += 1,
            Some(false) => private += 1,
            None => {}
        }
    }
    assert!(
        public > 0 && private > 0,
        "stdlib blob is uniform: {public} public, {private} private — \
         build.rs is emitting a constant, not the recorded bit"
    );
}
