//! Precompile the AL stdlib at `cargo build` time and emit it as a single
//! generated Rust source file (`$OUT_DIR/stdlib_generated.rs`) consisting
//! entirely of `const`/`static` arrays. There is no bincode, no serde, no
//! runtime deserialization — the binary's `.rodata` IS the stdlib.
//!
//! Any error in `src/std/**` (including `PreludeBindings::capture` shape
//! mismatches like a deleted `True` constructor) fails the *cargo build* with
//! the diagnostic text.

use std::fmt::Write as _;
use std::path::PathBuf;

use al_core::static_ir::flatten::{FlatPools, flatten, reserved_sorted};
use al_core::static_ir::{SConst, Slice};
use al_core::types::{
    ArenaSlice, DefinitionLocation, EntityKind, InferEngine, NO_STR, QuantVar, Scheme, TypeBody,
    TypeInfo, TypeNode, ValueKind,
};
use al_core::{PrecompileOutput, PreludeBindings, TypeId};

fn main() {
    // One rerun-if-changed per file: a directory path alone doesn't reliably
    // pick up edits to existing files, and the generated `stdlib::*` consts
    // must track the AL source exactly for the Rust-side bindings to be sound.
    for entry in walk_std("../al_core/src/std") {
        println!("cargo:rerun-if-changed={}", entry.display());
    }
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    let (pre, engine) = match al_core::precompile_stdlib() {
        Ok(p) => p,
        Err(e) => panic!("\n\n{e}\n"),
    };
    let pools = flatten(&pre, &engine);
    let reserved = reserved_sorted(&pre.reserved);

    let mut src = String::with_capacity(256 * 1024);
    writeln!(src, "// generated by build.rs — do not edit").unwrap();
    writeln!(
        src,
        "use al_core::static_ir::*;\n\
         use al_core::types::*;\n\
         use al_core::bytecode::Op;\n\
         use al_core::{{PreludeBindings, TypeRef, CtorRef, TypeId}};\n"
    )
    .unwrap();

    emit_prelude(&mut src, &pre.prelude);
    emit_stdlib_templates(&mut src, &pre, &engine);
    emit_static_slice(&mut src, "RESERVED", "&str", reserved.iter().map(|s| q(s)));
    writeln!(
        src,
        "pub const NEXT_TYPE_ID: TypeId = {};",
        tid(pre.next_type_id)
    )
    .unwrap();
    writeln!(
        src,
        "pub const STDLIB_LOCAL_COUNT: i32 = {};",
        pre.blob.local_count
    )
    .unwrap();

    emit_pools(&mut src, &pools);

    // The single handle.
    writeln!(
        src,
        "pub static STDLIB: StaticStdlib = StaticStdlib {{\n    \
         str_pool: STR_POOL, str_slice_pool: STR_SLICE_POOL, byte_pool: BYTE_POOL,\n    \
         nodes: NODES, children: CHILDREN,\n    \
         quants: QUANTS, str_slices: STR_SLICES, type_params: TYPE_PARAMS, variant_fields: VARIANT_FIELDS, variants: VARIANTS,\n    \
         schemes: SCHEMES, typeinfos: TYPEINFOS,\n    \
         stypeexport_pool: STYPEEXPORT_POOL, sexport_pool: SEXPORT_POOL, modules: MODULES, typeinfo_by_name: TYPEINFO_BY_NAME,\n    \
         code: CODE, functions: FUNCTIONS, constants: CONSTANTS,\n    \
         prelude: &PRELUDE, reserved: RESERVED, next_type_id: NEXT_TYPE_ID, local_count: STDLIB_LOCAL_COUNT,\n\
         }};"
    )
    .unwrap();

    std::fs::write(out_dir.join("stdlib_generated.rs"), &src)
        .unwrap_or_else(|e| panic!("write stdlib_generated.rs failed: {e}"));
}

// ---------------------------------------------------------------------------
// Emitters
// ---------------------------------------------------------------------------

fn walk_std(root: &str) -> Vec<PathBuf> {
    let mut out = vec![PathBuf::from(root)];
    let mut stack = vec![PathBuf::from(root)];
    while let Some(dir) = stack.pop() {
        for entry in
            std::fs::read_dir(&dir).unwrap_or_else(|e| panic!("build.rs: read_dir {dir:?}: {e}"))
        {
            let entry = entry.unwrap_or_else(|e| panic!("build.rs: walk {dir:?}: {e}"));
            let p = entry.path();
            if p.is_dir() {
                stack.push(p.clone());
            }
            out.push(p);
        }
    }
    out
}

fn q(s: &str) -> String {
    format!("{s:?}")
}

fn tid(id: TypeId) -> String {
    format!("TypeId({})", id.0)
}

/// `lit!(Type: field = expr, ...)` → `"Type { field: <expr>, ... }"`.
macro_rules! lit {
    ($T:ident : $($f:ident = $e:expr),+ $(,)?) => {
        format!(concat!(stringify!($T), " {{ ", $(stringify!($f), ": {}, ",)+ "}}"), $($e),+)
    };
}

fn slice(sl: Slice) -> String {
    lit!(Slice: start = sl.start, len = sl.len)
}

fn aslice<P>(sl: ArenaSlice<P>) -> String {
    format!("ArenaSlice::new({}, {})", sl.start, sl.len)
}

fn typenode(n: &TypeNode) -> String {
    match *n {
        TypeNode::Var(id) => format!("TypeNode::Var({id})"),
        TypeNode::Bound(i) => format!("TypeNode::Bound({i})"),
        TypeNode::Con { id, name, args } => {
            format!(
                "TypeNode::Con {{ id: {}, name: {name}, args: {} }}",
                tid(id),
                aslice(args)
            )
        }
        TypeNode::Fun { params, ret } => {
            format!("TypeNode::Fun {{ params: {}, ret: {ret} }}", aslice(params))
        }
        TypeNode::Tuple { elems } => format!("TypeNode::Tuple {{ elems: {} }}", aslice(elems)),
    }
}

fn emit_static_slice<I: Iterator<Item = String>>(out: &mut String, name: &str, ty: &str, items: I) {
    writeln!(out, "pub static {name}: &[{ty}] = &[").unwrap();
    for it in items {
        writeln!(out, "    {it},").unwrap();
    }
    writeln!(out, "];").unwrap();
}

/// `PascalCase` → `SCREAMING_SNAKE` for generated const identifiers.
fn screaming_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let mut prev_lower = false;
    for c in s.chars() {
        if c.is_uppercase() && prev_lower {
            out.push('_');
        }
        out.extend(c.to_uppercase());
        prev_lower = c.is_lowercase() || c.is_ascii_digit();
    }
    out
}

/// Emit `pub mod stdlib { pub mod <module> { pub static <CTOR>: VariantTemplate
/// = ... } }` for every constructor of every stdlib type. The const path
/// (e.g. `stdlib::net::SOCKET_ADDRESS`) is the binding surface — Rust code that
/// references one fails to compile if the AL definition is renamed or removed.
fn emit_stdlib_templates(out: &mut String, pre: &PrecompileOutput, eng: &InferEngine) {
    // Collect every (module path segments, rendered static) pair first so we
    // can emit nested `mod` blocks for paths like `net/socket` in a single
    // sorted pass. Only modules that contribute at least one constructor get a
    // `mod` block, but we still open parent mods (e.g. `net`) when only their
    // children carry constructors.
    let mut entries: Vec<(Vec<&str>, String)> = Vec::new();
    for (key, iface) in &pre.blob.interfaces {
        let segs: Vec<&str> = if key == "al" {
            vec!["prelude"]
        } else if let Some(rest) = key.strip_prefix("al/") {
            rest.split('/').collect()
        } else {
            continue;
        };
        for (type_name, ti) in &iface.types {
            let Some(variants) = ti.variants() else {
                continue;
            };
            for v in &eng.variants[variants.range()] {
                let variant_name = eng.str(v.name);
                let labels: Vec<String> = eng.variant_fields[v.fields.range()]
                    .iter()
                    .map(|f| q(eng.str(f.label)))
                    .collect();
                let line = format!(
                    "pub static {}: VariantTemplate = VariantTemplate {{ \
                     type_id: {}, type_name: {}, variant_name: {}, labels: &[{}] }};",
                    screaming_snake(variant_name),
                    tid(ti.id),
                    q(type_name),
                    q(variant_name),
                    labels.join(", "),
                );
                entries.push((segs.clone(), line));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    writeln!(out, "pub mod stdlib {{").unwrap();
    writeln!(out, "    use al_core::{{VariantTemplate, TypeId}};").unwrap();
    let mut open: Vec<&str> = Vec::new();
    for (segs, line) in &entries {
        // Close mods until `open` is a prefix of `segs`.
        while !segs.starts_with(&open) {
            open.pop();
            writeln!(out, "    {:indent$}}}", "", indent = 4 * open.len()).unwrap();
        }
        // Open mods down to `segs`.
        for seg in &segs[open.len()..] {
            writeln!(
                out,
                "    {:indent$}pub mod {seg} {{ use super::*;",
                "",
                indent = 4 * open.len()
            )
            .unwrap();
            open.push(seg);
        }
        writeln!(out, "    {:indent$}{line}", "", indent = 4 * open.len()).unwrap();
    }
    while open.pop().is_some() {
        writeln!(out, "    {:indent$}}}", "", indent = 4 * open.len()).unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn emit_prelude(out: &mut String, p: &PreludeBindings) {
    writeln!(
        out,
        "pub const PRELUDE: PreludeBindings = PreludeBindings {{"
    )
    .unwrap();
    for (n, r) in p.type_fields() {
        let v = lit!(TypeRef: id = tid(r.id), name = format_args!("{:?}", r.name));
        writeln!(out, "    {n}: {v},").unwrap();
    }
    for (n, c) in p.ctor_fields() {
        let v =
            lit!(CtorRef: type_id = tid(c.type_id), variant_idx = c.variant_idx, arity = c.arity);
        writeln!(out, "    {n}: {v},").unwrap();
    }
    writeln!(out, "}};").unwrap();
}

fn opt_constraint(c: Option<al_core::types::Constraint>) -> String {
    match c {
        Some(c) => format!("Some(Constraint::{c:?})"),
        None => "None".into(),
    }
}

fn emit_pools(out: &mut String, p: &FlatPools) {
    emit_static_slice(out, "STR_POOL", "&str", p.str_pool.iter().map(|s| q(s)));
    emit_static_slice(
        out,
        "STR_SLICE_POOL",
        "u32",
        p.str_slice_pool.iter().map(|i| i.to_string()),
    );
    emit_static_slice(
        out,
        "BYTE_POOL",
        "u8",
        p.byte_pool.iter().map(|b| b.to_string()),
    );

    emit_static_slice(out, "NODES", "TypeNode", p.nodes.iter().map(typenode));
    emit_static_slice(
        out,
        "CHILDREN",
        "u32",
        p.children.iter().map(|i| i.to_string()),
    );
    emit_static_slice(out, "QUANTS", "QuantVar", p.quants.iter().map(quantvar));
    emit_static_slice(
        out,
        "STR_SLICES",
        "u32",
        p.str_slices.iter().map(|i| i.to_string()),
    );
    emit_static_slice(
        out,
        "TYPE_PARAMS",
        "TypeParam",
        p.type_params
            .iter()
            .map(|tp| lit!(TypeParam: name = tp.name, id = -1)),
    );
    emit_static_slice(
        out,
        "VARIANT_FIELDS",
        "VariantField",
        p.variant_fields
            .iter()
            .map(|f| lit!(VariantField: label = f.label, ty = f.ty)),
    );
    emit_static_slice(
        out,
        "VARIANTS",
        "Variant",
        p.variants
            .iter()
            .map(|v| lit!(Variant: name = v.name, fields = aslice(v.fields))),
    );

    emit_static_slice(out, "SCHEMES", "Scheme", p.schemes.iter().map(scheme));
    emit_static_slice(
        out,
        "TYPEINFOS",
        "TypeInfo",
        p.typeinfos.iter().map(typeinfo),
    );

    emit_static_slice(
        out,
        "STYPEEXPORT_POOL",
        "STypeExport",
        p.stypeexport_pool
            .iter()
            .map(|e| lit!(STypeExport: name = e.name, info = e.info)),
    );
    emit_static_slice(
        out,
        "SEXPORT_POOL",
        "SExport",
        p.sexport_pool
            .iter()
            .map(|e| lit!(SExport: name = e.name, scheme = e.scheme, local_slot = format_args!("{:?}", e.local_slot))),
    );
    emit_static_slice(
        out,
        "MODULES",
        "(&str, SModule)",
        p.modules.iter().map(|(k, m)| {
            format!(
                "({}, SModule {{ types: {}, values: {}, private_names: {}, path: {} }})",
                q(k),
                slice(m.types),
                slice(m.values),
                slice(m.private_names),
                slice(m.path)
            )
        }),
    );
    emit_static_slice(
        out,
        "TYPEINFO_BY_NAME",
        "(&str, u32)",
        p.typeinfo_by_name
            .iter()
            .map(|(n, i)| format!("({}, {})", q(n), i)),
    );

    emit_static_slice(
        out,
        "CODE",
        "SInstruction",
        p.code
            .iter()
            .map(|i| {
                lit!(SInstruction: op = format_args!("SOp::{:?}", i.op), operand = i.operand, a = i.a, b = i.b)
            }),
    );
    emit_static_slice(
        out,
        "FUNCTIONS",
        "SFunction",
        p.functions.iter().map(|f| {
            lit!(SFunction: name = f.name, arity = f.arity, locals = f.locals,
                 capture_count = f.capture_count, code_start = f.code_start, code_len = f.code_len)
        }),
    );
    emit_static_slice(out, "CONSTANTS", "SConst", p.constants.iter().map(sconst));
}

fn quantvar(qv: &QuantVar) -> String {
    let name = if qv.name == NO_STR {
        "NO_STR".into()
    } else {
        qv.name.to_string()
    };
    lit!(QuantVar: constraint = opt_constraint(qv.constraint), name = name, origin_id = "None")
}

fn valuekind(k: ValueKind) -> String {
    match k {
        ValueKind::Local => "ValueKind::Local".into(),
        ValueKind::ModuleFn => "ValueKind::ModuleFn".into(),
        ValueKind::Builtin { op } => format!("ValueKind::Builtin {{ op: Op::{op:?} }}"),
        ValueKind::Constructor {
            type_name,
            type_id,
            variant_idx,
            arity,
            field_labels,
        } => format!(
            "ValueKind::Constructor {{ type_name: {type_name}, type_id: {}, variant_idx: {variant_idx}, arity: {arity}, field_labels: {} }}",
            tid(type_id),
            aslice(field_labels)
        ),
    }
}

fn entitykind(e: EntityKind) -> &'static str {
    match e {
        EntityKind::Value => "EntityKind::Value",
        EntityKind::Function => "EntityKind::Function",
        EntityKind::Constant => "EntityKind::Constant",
        EntityKind::Constructor => "EntityKind::Constructor",
        EntityKind::Type => "EntityKind::Type",
        EntityKind::ModuleAlias => "EntityKind::ModuleAlias",
        EntityKind::Field => "EntityKind::Field",
    }
}

/// Emit the declaring `DefinitionLocation` so cross-module goto-def /
/// find-references can land inside a precompiled `al/*` module. The `module`
/// `ArenaSlice` indexes the static string-slice pool, which `seed_static`
/// memcpies back as the live arena's prefix, so the location stays valid.
fn def_lit(d: Option<DefinitionLocation>) -> String {
    match d {
        None => "None".to_string(),
        Some(dl) => format!(
            "Some(DefinitionLocation {{ line: {}, column: {}, end_col: {}, module: {}, entity: {} }})",
            dl.line,
            dl.column,
            dl.end_col,
            aslice(dl.module),
            entitykind(dl.entity),
        ),
    }
}

fn scheme(s: &Scheme) -> String {
    lit!(Scheme: quantified = aslice(s.quantified), ty = s.ty, kind = valuekind(s.kind), def = def_lit(s.def))
}

fn typeinfo(ti: &TypeInfo) -> String {
    let body = match ti.body {
        TypeBody::External => "TypeBody::External".into(),
        TypeBody::Unresolved => panic!(
            "build.rs: stdlib type has Unresolved body after precompile — hydration missed it"
        ),
        TypeBody::Alias { target } => format!("TypeBody::Alias {{ target: {target} }}"),
        TypeBody::Custom { variants } => {
            format!("TypeBody::Custom {{ variants: {} }}", aslice(variants))
        }
    };
    lit!(TypeInfo: id = tid(ti.id), name = ti.name, module = aslice(ti.module),
         type_params = aslice(ti.type_params), body = body)
}

fn sconst(c: &SConst) -> String {
    match *c {
        SConst::Int(n) => format!("SConst::Int({n}i64)"),
        SConst::Float(f) => format!("SConst::Float({}f64)", float_lit(f)),
        SConst::Bool(b) => format!("SConst::Bool({b})"),
        SConst::Str(i) => format!("SConst::Str({i})"),
        SConst::StrArray(sl) => format!("SConst::StrArray({})", slice(sl)),
        SConst::Binary(sl, bit_len) => format!("SConst::Binary({}, {bit_len}u64)", slice(sl)),
    }
}

fn float_lit(f: f64) -> String {
    if f.is_nan() {
        "f64::NAN".into()
    } else if f.is_infinite() {
        if f > 0.0 {
            "f64::INFINITY"
        } else {
            "f64::NEG_INFINITY"
        }
        .into()
    } else {
        // Debug formatting of f64 is round-trippable.
        format!("{f:?}")
    }
}
