[package]
name = "al"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
al_core = { path = "../al_core" }
clap = { version = "4", features = ["derive"] }
clap_mangen = "0.3"
libc = "0.2"
memchr = "2"
mio = { version = "1", features = ["os-poll", "os-ext"] }
percent-encoding = "2"
rustyline = "14"
serde_json = "1"
smallvec = "1.15"
socket2 = { version = "0.5", features = ["all"] }
indexmap = { workspace = true }
ureq = "2"

[build-dependencies]
al_core = { path = "../al_core" }

[dev-dependencies]
al_core = { path = "../al_core", features = ["alloc-counter"] }
serde_json = "1"

[[bin]]
name = "al"
path = "src/main.rs"

