use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum Kind {
    Eof,
    Error,
    Identifier,
    LiteralNumber,
    LiteralString,
    LiteralChar,
    InterpStringStart,
    InterpStringPart,
    InterpStringEnd,
    LogicalAnd,
    LogicalOr,
    BitwiseAnd,
    BitwiseOr,
    BitwiseXor,
    BitwiseNot,
    KwComptime,
    KwConst,
    KwEnum,
    KwError,
    KwIf,
    KwElse,
    KwFunction,
    KwImport,
    KwFrom,
    KwTrue,
    KwFalse,
    KwExport,
    KwStruct,
    KwIn,
    KwMatch,
    KwNone,
    KwOr,
    PuncArrow,
    PuncComma,
    PuncColon,
    PuncSemicolon,
    PuncDot,
    PuncDotdot,
    PuncEllipsis,
    PuncOpenParen,
    PuncCloseParen,
    PuncOpenBrace,
    PuncCloseBrace,
    PuncOpenBracket,
    PuncCloseBracket,
    PuncQuestionMark,
    PuncExclamationMark,
    PuncAt,
    PuncEquals,
    PuncEqualsComparator,
    PuncNotEqual,
    PuncGt,
    PuncLt,
    PuncGte,
    PuncLte,
    PuncPlus,
    PuncPlusplus,
    PuncMinus,
    PuncMinusminus,
    PuncMul,
    PuncDiv,
    PuncMod,
    #[allow(non_camel_case_types)]
    _End_,
}

impl fmt::Display for Kind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            Kind::Eof => "EOF",
            Kind::Error => "<error>",
            Kind::Identifier => "identifier",
            Kind::LiteralNumber => "number",
            Kind::LiteralString => "string",
            Kind::LiteralChar => "char",
            Kind::InterpStringStart => "interpolated string start",
            Kind::InterpStringPart => "interpolated string part",
            Kind::InterpStringEnd => "interpolated string end",
            Kind::LogicalAnd => "&&",
            Kind::LogicalOr => "||",
            Kind::BitwiseAnd => "&",
            Kind::BitwiseOr => "|",
            Kind::BitwiseXor => "^",
            Kind::BitwiseNot => "~",
            Kind::KwComptime => "comptime",
            Kind::KwConst => "const",
            Kind::KwEnum => "enum",
            Kind::KwError => "error",
            Kind::KwIf => "if",
            Kind::KwElse => "else",
            Kind::KwFunction => "fn",
            Kind::KwImport => "import",
            Kind::KwFrom => "from",
            Kind::KwTrue => "true",
            Kind::KwFalse => "false",
            Kind::KwExport => "export",
            Kind::KwStruct => "struct",
            Kind::KwIn => "in",
            Kind::KwMatch => "match",
            Kind::KwNone => "none",
            Kind::KwOr => "or",
            Kind::PuncArrow => "->",
            Kind::PuncComma => ",",
            Kind::PuncColon => ":",
            Kind::PuncSemicolon => ";",
            Kind::PuncDot => ".",
            Kind::PuncDotdot => "..",
            Kind::PuncEllipsis => "...",
            Kind::PuncOpenParen => "(",
            Kind::PuncCloseParen => ")",
            Kind::PuncOpenBrace => "{",
            Kind::PuncCloseBrace => "}",
            Kind::PuncOpenBracket => "[",
            Kind::PuncCloseBracket => "]",
            Kind::PuncQuestionMark => "?",
            Kind::PuncExclamationMark => "!",
            Kind::PuncAt => "@",
            Kind::PuncEquals => "=",
            Kind::PuncEqualsComparator => "==",
            Kind::PuncNotEqual => "!=",
            Kind::PuncGt => ">",
            Kind::PuncLt => "<",
            Kind::PuncGte => ">=",
            Kind::PuncLte => "<=",
            Kind::PuncPlus => "+",
            Kind::PuncPlusplus => "++",
            Kind::PuncMinus => "-",
            Kind::PuncMinusminus => "--",
            Kind::PuncMul => "*",
            Kind::PuncDiv => "/",
            Kind::PuncMod => "%",
            Kind::_End_ => "<end>",
        };
        f.write_str(s)
    }
}
