export enum TokenKind {
  // Keywords
  KW_FUNCTION = "KW_FUNCTION",
  KW_RETURN = "KW_RETURN",
  KW_BREAK = "KW_BREAK",
  KW_CONTINUE = "KW_CONTINUE",
  KW_IMPORT = "KW_IMPORT",
  KW_FROM = "KW_FROM",
  KW_TRUE = "KW_TRUE",
  KW_FALSE = "KW_FALSE",
  KW_ASSERT = "KW_ASSERT",
  KW_EXPORT = "KW_EXPORT",
  KW_STRUCT = "KW_STRUCT",
  KW_IN = "KW_IN",
  KW_NONE = "KW_NONE",
  KW_CONST = "KW_CONST",
  KW_IF = "KW_IF",
  KW_ELSE = "KW_ELSE",
  KW_THROW = "KW_THROW",
  KW_OR = "KW_OR",
  KW_FOR = "KW_FOR",
  KW_ENUM = "KW_ENUM",
  KW_MATCH = "KW_MATCH",
  KW_AS = "KW_AS",
  KW_COMPTIME = "KW_COMPTIME",

  // Punctuation
  PUNC_ARROW = "PUNC_ARROW",
  PUNC_DOTDOT = "PUNC_DOTDOT",
  PUNC_OPEN_PAREN = "PUNC_OPEN_PAREN",
  PUNC_CLOSE_PAREN = "PUNC_CLOSE_PAREN",
  PUNC_OPEN_BRACE = "PUNC_OPEN_BRACE",
  PUNC_CLOSE_BRACE = "PUNC_CLOSE_BRACE",
  PUNC_OPEN_BRACKET = "PUNC_OPEN_BRACKET",
  PUNC_CLOSE_BRACKET = "PUNC_CLOSE_BRACKET",
  PUNC_COMMA = "PUNC_COMMA",
  PUNC_DOT = "PUNC_DOT",
  PUNC_COLON = "PUNC_COLON",
  PUNC_COLON_EQUALS = "PUNC_COLON_EQUALS",
  PUNC_SEMICOLON = "PUNC_SEMICOLON",
  PUNC_EQUALS = "PUNC_EQUALS",
  PUNC_EQUALS_EQUALS = "PUNC_EQUALS_EQUALS",
  PUNC_BANG = "PUNC_BANG",
  PUNC_BANG_EQUALS = "PUNC_BANG_EQUALS",
  PUNC_GREATER = "PUNC_GREATER",
  PUNC_GREATER_EQUALS = "PUNC_GREATER_EQUALS",
  PUNC_LESS = "PUNC_LESS",
  PUNC_LESS_EQUALS = "PUNC_LESS_EQUALS",
  PUNC_PLUS = "PUNC_PLUS",
  PUNC_MINUS = "PUNC_MINUS",
  PUNC_STAR = "PUNC_STAR",
  PUNC_SLASH = "PUNC_SLASH",
  PUNC_PERCENT = "PUNC_PERCENT",
  PUNC_QUESTION = "PUNC_QUESTION",
  PUNC_AND = "PUNC_AND",
  PUNC_OR = "PUNC_OR",
  PUNC_PIPE = "PUNC_PIPE",

  // Literals
  LITERAL_STRING = "LITERAL_STRING",
  LITERAL_NUMBER = "LITERAL_NUMBER",
  LITERAL_BOOLEAN = "LITERAL_BOOLEAN",
  IDENTIFIER = "IDENTIFIER",

  // Special
  EOF = "EOF",
}

export function tokenKindToString(kind: TokenKind): string {
  const map: Record<TokenKind, string> = {
    [TokenKind.KW_FUNCTION]: "function",
    [TokenKind.KW_RETURN]: "return",
    [TokenKind.KW_BREAK]: "break",
    [TokenKind.KW_CONTINUE]: "continue",
    [TokenKind.KW_IMPORT]: "import",
    [TokenKind.KW_FROM]: "from",
    [TokenKind.KW_TRUE]: "true",
    [TokenKind.KW_FALSE]: "false",
    [TokenKind.KW_ASSERT]: "assert",
    [TokenKind.KW_EXPORT]: "export",
    [TokenKind.KW_STRUCT]: "struct",
    [TokenKind.KW_IN]: "in",
    [TokenKind.KW_NONE]: "none",
    [TokenKind.KW_CONST]: "const",
    [TokenKind.KW_IF]: "if",
    [TokenKind.KW_ELSE]: "else",
    [TokenKind.KW_THROW]: "throw",
    [TokenKind.KW_OR]: "or",
    [TokenKind.KW_FOR]: "for",
    [TokenKind.KW_ENUM]: "enum",
    [TokenKind.KW_MATCH]: "match",
    [TokenKind.KW_AS]: "as",
    [TokenKind.KW_COMPTIME]: "comptime",
    [TokenKind.PUNC_ARROW]: "=>",
    [TokenKind.PUNC_DOTDOT]: "..",
    [TokenKind.PUNC_OPEN_PAREN]: "(",
    [TokenKind.PUNC_CLOSE_PAREN]: ")",
    [TokenKind.PUNC_OPEN_BRACE]: "{",
    [TokenKind.PUNC_CLOSE_BRACE]: "}",
    [TokenKind.PUNC_OPEN_BRACKET]: "[",
    [TokenKind.PUNC_CLOSE_BRACKET]: "]",
    [TokenKind.PUNC_COMMA]: ",",
    [TokenKind.PUNC_DOT]: ".",
    [TokenKind.PUNC_COLON]: ":",
    [TokenKind.PUNC_COLON_EQUALS]: ":=",
    [TokenKind.PUNC_SEMICOLON]: ";",
    [TokenKind.PUNC_EQUALS]: "=",
    [TokenKind.PUNC_EQUALS_EQUALS]: "==",
    [TokenKind.PUNC_BANG]: "!",
    [TokenKind.PUNC_BANG_EQUALS]: "!=",
    [TokenKind.PUNC_GREATER]: ">",
    [TokenKind.PUNC_GREATER_EQUALS]: ">=",
    [TokenKind.PUNC_LESS]: "<",
    [TokenKind.PUNC_LESS_EQUALS]: "<=",
    [TokenKind.PUNC_PLUS]: "+",
    [TokenKind.PUNC_MINUS]: "-",
    [TokenKind.PUNC_STAR]: "*",
    [TokenKind.PUNC_SLASH]: "/",
    [TokenKind.PUNC_PERCENT]: "%",
    [TokenKind.PUNC_QUESTION]: "?",
    [TokenKind.PUNC_AND]: "&&",
    [TokenKind.PUNC_OR]: "||",
    [TokenKind.PUNC_PIPE]: "|",
    [TokenKind.LITERAL_STRING]: "string",
    [TokenKind.LITERAL_NUMBER]: "number",
    [TokenKind.LITERAL_BOOLEAN]: "boolean",
    [TokenKind.IDENTIFIER]: "identifier",
    [TokenKind.EOF]: "EOF",
  };

  return map[kind];
}

export interface Token {
  kind: TokenKind;
  literal?: string;
  line: number;
  column: number;
}

export const KEYWORDS: Record<string, TokenKind> = {
  fn: TokenKind.KW_FUNCTION,
  return: TokenKind.KW_RETURN,
  break: TokenKind.KW_BREAK,
  continue: TokenKind.KW_CONTINUE,
  import: TokenKind.KW_IMPORT,
  from: TokenKind.KW_FROM,
  true: TokenKind.KW_TRUE,
  false: TokenKind.KW_FALSE,
  assert: TokenKind.KW_ASSERT,
  export: TokenKind.KW_EXPORT,
  struct: TokenKind.KW_STRUCT,
  in: TokenKind.KW_IN,
  none: TokenKind.KW_NONE,
  const: TokenKind.KW_CONST,
  if: TokenKind.KW_IF,
  else: TokenKind.KW_ELSE,
  throw: TokenKind.KW_THROW,
  or: TokenKind.KW_OR,
  for: TokenKind.KW_FOR,
  enum: TokenKind.KW_ENUM,
  match: TokenKind.KW_MATCH,
  as: TokenKind.KW_AS,
  comptime: TokenKind.KW_COMPTIME,
};
