module compiler

import datatypes

pub struct Scanner {
pub mut:
	absolute_file_path string // The absolute path of the file
	text               string // The whole text of the file
	pos                int    // The current position in the text
	line               int    // The current line in the text
	// The messages generated by the scanner
	messages datatypes.Set[&Message] = unsafe { datatypes.Set[Message]{} }
}

pub fn new_scanner(absolute_file_path string, text string) Scanner {
	return Scanner{
		absolute_file_path: absolute_file_path
		text: text
		pos: 0
		line: 1
	}
}

pub fn (scanner Scanner) peek() byte {
	return scanner.text[scanner.pos]
}

pub fn (scanner Scanner) look_ahead(n int) string {
	return (scanner.text[scanner.pos..scanner.pos + n]).str()
}

pub fn (scanner Scanner) scan() {
	assert scanner.pos == 0
	assert scanner.line == 1

	// Scan the text
	for scanner.pos < scanner.text.len {
		mut c := scanner.text[scanner.pos]
		mut next_c := if scanner.pos + 1 < scanner.text.len {
			scanner.text[scanner.pos + 1]
		} else {
			0
		}

		//
	}
}

// scan_underscore scans an underscore
fn (scanner Scanner) scan_plus() {
	token := new_token(
		.math_plus,
	)
}
